import os
import re
from pathlib import Path


def test_no_runtime_controllers_imports():
    """
    Ensure application runtime code does not import from mmx_engineering_spec_manager.controllers.*
    tests/test_controllers is excluded by pytest.ini, so we only scan non-test runtime code.
    """
    root = Path(__file__).resolve().parents[2] / "mmx_engineering_spec_manager"
    pattern = re.compile(r"mmx_engineering_spec_manager\.controllers")

    bad_files = []
    for path in root.rglob("*.py"):
        # Skip the controllers folder itself and tests
        if "/controllers/" in str(path.as_posix()):
            continue
        if "/tests/" in str(path.as_posix()):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue
        # Quick ignore: autogenerated __init__ with __all__ only ok
        if pattern.search(text):
            bad_files.append(str(path.relative_to(root.parent)))
    assert not bad_files, f"Found runtime imports of controllers in: {bad_files}"
